baseURL = "http://example.org/"
languageCode = "en-us"
title = "Brian's Portfolio"
theme = "basic"
disqusShortname = "pphugodemo"

[params]
  author = "Brian Hogan"
  description = "My portfolio site"
  gh_url = "https://api.github.com/users"
  gh_user = ""

[permalinks]
  posts = "posts/:year/:month/:slug/"
  year = "/posts/:slug/"
  month = "/posts/:slug/"

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"

